name: Zoho Tasker release builder
on:
  push:
    branches:
      - 'release'
jobs:
  build-win:
    name: Build Windows Installer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Read current version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Build electron
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload setup file
        uses: actions/upload-artifact@v3
        with:
          name: zohotasker-v${{ steps.package-version.outputs.current-version }}-win-setup
          path: dist_electron/*.exe