name: Zoho Tasker release builder
on:
  push:
    branches:
      - 'release'
jobs:
  build-app:
    name: Checkout and build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Build electron
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload setup file
        uses: actions/upload-artifact@v3
        with:
          name: zoho-tasker-setup
          path: dist_electron/*.exe