name: Zoho Tasker release builder
on:
  push:
    branches:
      - 'release'
    tags:
      - v*
jobs:
  build-win:
    name: Build Windows Installer
    runs-on: windows-latest
    outputs:
      artifactName: ${{ steps.artifact.outputs.artifactName }}
      versionNumber: ${{ steps.version.outputs.versionNumber }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node v16 environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: yarn install

      # - name: Read current version
      #   uses: nyaa8/package-version@v1

      - name: Build electron
        run: yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload setup file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: zohotasker-win-setup
      #     path: dist_electron/*.exe

  #     - name: Set artifact name output
  #       id: artifact
  #       run: echo "artifactName=zohotasker-win-setup" >> $GITHUB_OUTPUT

  #     - name: Set version output
  #       id: version
  #       run: echo "versionNumber=${{ env.PACKAGE_VERSION }}" >> $GITHUB_OUTPUT

  # create-release:
  #   name: Create release
  #   runs-on: windows-latest
  #   needs: build-win
  #   steps:
  #     - name: Reading variables
  #       run: |
  #         echo ${{ needs.build-win.outputs.artifactName }}
  #         echo ${{ needs.build-win.outputs.versionNumber }}
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: ${{ needs.build-win.outputs.artifactName }}
      
      # - name: Create release
      #   id: create-release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ needs.build-win.outputs.versionNumber }}
      #     release_name: Zoho Tasker v${{ needs.build-win.outputs.versionNumber }}

      # - name: Upload release assets
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./${{ needs.build-win.outputs.artifactName }}
      #     asset_name: zohotasker-v${{ needs.build-win.outputs.versionNumber }}-win-setup
      #     asset_content_type: application/zip