name: Zoho Tasker release builder
on:
  push:
    branches:
      - 'release'
jobs:
  build-win:
    name: Build Windows Installer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Read current version
        uses: nyaa8/package-version@v1
      - name: Build electron
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload setup file
        uses: actions/upload-artifact@v3
        with:
          name: zohotasker-setup
          path: dist_electron/*.exe
      - name: Create release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: Zoho Tasker v${{ env.PACKAGE_VERSION }}