name: Zoho Tasker release builder
on:
  push:
    tags:
      - v*
jobs:
  build-win:
    name: Build Windows Installer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node v16 environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: yarn install

      - name: Build and create release
        run: yarn electron:publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}